### ISSUE TITLE
Professor RMP link goes to wrong professor

### ISSUE THREAD

**Issue by EricPedley** [jogplus/zotcourse#19]
The professor for the Fall 2021 Math 3A Lecture D is "Zhang, Y" and the RMP link goes to Yu Zhang in the management department (https://www.ratemyprofessors.com/ShowRatings.jsp?tid=1589591) instead of the Yue Zhang in the math department (https://www.ratemyprofessors.com/ShowRatings.jsp?tid=2091423). I don't know for sure if "Zhang, Y" means Yue Zhang instead of Yu Zhang but it probably makes more sense that the math department professor is teaching it, not the management department professor, so I would double-check if that link is right or if the process for generating those links is working correctly.

**Comment by jogplus** [comment]
Hi Eric, unfortunately Websoc only provides me with the professor's last name and first name initial so when I use a fuzzy search to match this name to the RMP name, there are sometimes multiple matches (as you mentioned). Additionally, I do not have access to the RMP prof department when performing this match. As a result there isn't much I can do about this problem without manually adding exceptions but this isn't something I would want to constantly maintain.

Thank you for letting me know about this though and let me know if you have any questions!
