### ISSUE TITLE
Save Last Username

### ISSUE THREAD

**Issue by AdRob5** [jogplus/zotcourse#3]
One thing that Antplanner does is save the last username you used to save your schedule. So when you click on "save", the field is pre-filled out with your last username. 

Not a huge thing, but it does save a bit of time. Especially when I save after making a few minor changes, it would make things a little faster if I didn't have to type in my username every time.

**Comment by jogplus** [comment]
Hi this was actually already implemented but required a page refresh to fully work. I have just published a workaround that should work better. Let me know what you think. Thank you for the suggestion!
