### ISSUE TITLE
XSS vulnerability

### ISSUE THREAD

**Issue by bkblanton** [jogplus/zotcourse#5]
Hey, I want to let you know that your app has a big XSS vulnerability. An attacker could make a user's browser run arbitrary code upon clicking a course in their schedule.

# How to reproduce

1.  Submit a POST request to /schedules/add, but add a "url" attribute to an element of the JSON form data. Example:
```json
[
    {
        "id": "05b0",
        "groupId": "34070",
        "title": "Lec CompSci  131",
        "start": "15:00",
        "end": "15:50",
        "color": "#85AAA5",
        "location": "SSH 100",
        "fullName": "PARLLEL DIST CMPTNG",
        "instructor": ["VEIDENBAUM, A."],
        "final": "Mon, Jun 10, 4:00-6:00pm",
        "dow": [1,3,5],
        "daysOfTheWeek": [1,3,5],
        "units": "4",
        "url": "javascript:alert('Just testing!');"
    }
]
```
2. Load the schedule and click on the course.

# Screenshot
Here's what happens in the example above:
![image](https://user-images.githubusercontent.com/12481078/53062023-4cbfce00-3474-11e9-9a17-3fb22f04cf95.png)

# Fix

Don't create links from user data. Escaping them as HTML is not enough.

**Comment by jogplus** [comment]
Thank you so much for this. It seems that the fullcalendar library automatically injects the url attribute into the event if it exists. I have just pushed a crude hotfix to remove the url attribute. I plan to implement more thorough input sanitization/validation when I get the chance. Please let me know if you find any other vulnerabilities.
