### ISSUE TITLE
Online Courses Adding Error

### ISSUE THREAD

**Issue by tongl2** [jogplus/zotcourse#6]
Online courses cannot be added due to the course time is TBA.
![image](https://user-images.githubusercontent.com/34897000/53226496-044d0f80-3630-11e9-92e3-7239aedd908d.png)

**Comment by jogplus** [comment]
Courses that have a TBA time cannot be placed on the calendar. If you are referring to 6D which has both a meeting time and is TBA, I am working on making it possible to be added.

**Comment by jogplus** [comment]
Added functionality to handle courses like 6D where it has both a meeting time and is TBA.
