### ISSUE TITLE
Schedules no longer loading

### ISSUE THREAD

**Issue by gvkhacha** [jogplus/zotcourse#8]
**Describe the bug**
No schedules are loading properly

**To Reproduce**
1. Add a few classes to the schedule
2. Save to some schedule name. (Green confirmation given that schedule is saved)
3. Clear or refresh the page.
4. Attempt to load that same schedule. (Schedule not found)

**Desktop:**
 - OS: Debian
 - Browser: Firefox

**Comment by jogplus** [comment]
Thank you for reporting this, there was an issue when I last deployed. It has been resolved now.
